spring:
  datasource:          #Fuente de datos
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: platzi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
      generate-ddL: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  #security:
    #user:
      #name: platzi
      #password: platzi